name: Run simple java test

on:
  workflow_dispatch:
    
jobs:
  test:
    name: Run java tests
    runs-on: ubuntu-20.04
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      # setup java8
      - name: Setup java8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      
      - name: Run Simple Test
        shell: bash
        run: |
          cd tests/
          java -ea SimpleTest
